name: 'Setup Rust'
description: 'Setup rust toolchain'
inputs:
  cache:
    description: 'Cache'
    required: false
    default: false
  aarch64-apple-darwin:
    description: 'aarch64-apple-darwin'
    required: false
    default: false
runs:
  using: "composite"
  steps: 
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    
    - name: Install aarch64-apple-darwin target
      if: ${{ inputs.aarch64-apple-darwin }}
      run: rustup target add aarch64-apple-darwin

    - name: Cache cargo registry
      uses: actions/cache@v3
      if: ${{ inputs.cache }}
      continue-on-error: false
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git            
          snapatac2-core/target/  
          snapatac2-python/target/  
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-